// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Nexxus Drako Multimedia

/**
 * Performance by world size (TODO M2; D19: measured and reported, not gated). For each
 * country count: world creation time, save time and size, and the time to simulate a year.
 *
 *   node scripts/measure-performance.ts [--seeds 5] [--years 5] [--out docs/validation/performance.md]
 */

import { mkdirSync, mkdtempSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { parseArgs } from 'node:util';
import { WorldSession } from '../packages/app/src/index.ts';
import { formatSeed, GENERATOR_VERSION, RULESET_VERSION } from '../packages/engine/src/index.ts';

const { values } = parseArgs({
  options: { seeds: { type: 'string' }, years: { type: 'string' }, out: { type: 'string' } },
});
const seedCount = Number(values.seeds ?? 5);
const years = Number(values.years ?? 5);
const sizes = [20, 50, 100, 196, 300, 500];
const dir = mkdtempSync(join(tmpdir(), 'nationwright-perf-'));
const started = performance.now();
const elapsed = () => `${((performance.now() - started) / 1000).toFixed(1)}s`;
const median = (xs: number[]) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)] ?? NaN;

interface Row {
  size: number;
  createMs: number[];
  yearMs: number[];
  saveMs: number[];
  saveMb: number[];
  regions: number[];
  playerPopulation: number[];
}

const rows: Row[] = [];
for (const size of sizes) {
  const row: Row = {
    size,
    createMs: [],
    yearMs: [],
    saveMs: [],
    saveMb: [],
    regions: [],
    playerPopulation: [],
  };
  for (let s = 0; s < seedCount; s++) {
    const seed = formatSeed(
      (BigInt(size * 1000 + s) * 0x9e3779b97f4a7c15n) & 0xffff_ffff_ffff_fffcn,
    );
    const path = join(dir, `${size}-${s}.nwsave`);
    const t0 = performance.now();
    const session = WorldSession.create({
      path,
      seed,
      settings: { countryCount: size },
      now: () => new Date('2026-09-25T12:00:00Z'),
    });
    row.createMs.push(performance.now() - t0);
    const t1 = performance.now();
    session.engine.advance(12 * years);
    row.yearMs.push((performance.now() - t1) / years);
    const t2 = performance.now();
    session.save();
    row.saveMs.push(performance.now() - t2);
    const demography = session.engine.world.slices.demography!;
    row.regions.push(demography.regions.length);
    row.playerPopulation.push(
      demography.regions.reduce((sum, r) => sum + r.cohorts.reduce((a, b) => a + b, 0), 0),
    );
    session.close();
    row.saveMb.push(statSync(path).size / 1e6);
    rmSync(path, { force: true });
  }
  rows.push(row);
  process.stderr.write(`[${elapsed()}] ${size} countries: ${seedCount} worlds measured\n`);
}
rmSync(dir, { recursive: true, force: true });

const f = (x: number, d = 0) => x.toFixed(d);
const report = `# Performance by world size

Generated by \`scripts/measure-performance.ts\` (generator v${GENERATOR_VERSION}, ruleset v${RULESET_VERSION})
on ${process.platform}/${process.arch}, Node ${process.versions.node}: ${seedCount} worlds per size, each simulated
for ${years} years. Medians. Reported, not gated (D19).

| Countries | Create world (ms) | Simulate 1 year (ms) | Save (ms) | Save file (MB) | Player regions | Player population |
|---|---|---|---|---|---|---|
${rows
  .map(
    (r) =>
      `| ${r.size} | ${f(median(r.createMs))} | ${f(median(r.yearMs))} | ${f(median(r.saveMs))} | ${f(median(r.saveMb), 1)} | ${median(r.regions)} | ${Math.round(median(r.playerPopulation)).toLocaleString('en-US')} |`,
  )
  .join('\n')}

World creation grows with the map (cells scale with the country count). Simulation time
depends mostly on the player's nation: its regions and the number of culture
combinations it tracks, not on the world's size, because foreign countries are not
simulated in detail yet (M3). Save size is dominated by the map layers and the player's
per-combination cohort counts (stored as JSON).

Total run: ${elapsed()}.
`;

if (values.out !== undefined) {
  mkdirSync(dirname(values.out), { recursive: true });
  writeFileSync(values.out, report);
  process.stderr.write(`wrote ${values.out}\n`);
} else {
  process.stdout.write(report);
}
